"""add styling column to form_setups

Revision ID: 96ebe3ebe0ad
Revises: 395d85e1de2e
Create Date: 2026-03-15 20:05:52.100256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96ebe3ebe0ad'
down_revision: Union[str, Sequence[str], None] = '395d85e1de2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_setups', sa.Column('styling', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_setups', 'styling')
    # ### end Alembic commands ###
